DATABASE_USERNAME = "user"
DATABASE_PASSWORD = "password"
DATABASE_HOST = "localhost"
DATABASE_PORT = "3306"
DATABASE_NAME = "projeto_integrador"

SQLALCHEMY_DATABASE_URI = f"mysql+pymysql://{DATABASE_USERNAME}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}?ssl_disabled=True"

SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = "sua_chave_secreta"